[shell_alias]
orbit = "go run -ldflags \"-X main.version=$(git describe --tags --dirty)\" ./cmd/orbit"

[tasks.clean]
run = "go clean"

[tasks.test]
run = "gotestsum ./..."

[tasks.fmt]
run = "go fmt ./..."

[tasks.vet]
depends = ["fmt"]
hide    = true  # use check
run     = "go vet ./..."

[tasks.fix]
depends = ["fmt"]
hide    = true  # use check
run     = "go fix ./..."

[tasks.golangci]
hide    = true  # use check
depends = ["fmt"]
run     = "golangci-lint run ./..."

[tasks.govulncheck]
hide    = true  # use check
depends = ["fmt"]
run     = "govulncheck ./..."

[tasks.fuzz]
usage = 'arg "<duration>" default="60s"'
run   = """
go test ./cmd/orbit/ -fuzz=FuzzNaturalLess -fuzztime=${usage_duration?}
go test ./cmd/orbit/ -fuzz=FuzzSplitChunk -fuzztime=${usage_duration?}
go test ./cmd/orbit/ -fuzz=FuzzCompareNumeric -fuzztime=${usage_duration?}
"""

[tasks.check]
depends = ["vet", "fix", "golangci", "govulncheck"]

[tasks.build]
depends = ["fmt"]
sources = ["**/*.go", "go.sum", "cmd/orbit/icon.png", "cmd/orbit/schema.json"]
outputs = ["bin/orbit"]
run     = "go build -ldflags \"-X main.version=$(git describe --tags --dirty)\" -o bin/orbit ./cmd/orbit"

[tasks.completions]
run = "eval $(go run ./cmd/orbit completion zsh)"

[env]
_.path = ["bin/"]

[deps]
go = { auto = true }

[tools]
go = "latest"
